// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD68dh01badnHl72P6qSKGyb7T9BWJDC6Y',
    appId: '1:565579818314:web:c978904304eb9a65878db3',
    messagingSenderId: '565579818314',
    projectId: 'voyage-73bab',
    authDomain: 'voyage-73bab.firebaseapp.com',
    storageBucket: 'voyage-73bab.appspot.com',
    measurementId: 'G-E20M9QDTNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCysw_fT3SH_xls_AvOxoKpNI77h7zHcEI',
    appId: '1:565579818314:android:2ed12d5ccb656c67878db3',
    messagingSenderId: '565579818314',
    projectId: 'voyage-73bab',
    storageBucket: 'voyage-73bab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAopEj_RbeDes8NtR0iyJ9hAOcoM5z7xSg',
    appId: '1:565579818314:ios:9ac2476754f59108878db3',
    messagingSenderId: '565579818314',
    projectId: 'voyage-73bab',
    storageBucket: 'voyage-73bab.appspot.com',
    iosClientId: '565579818314-a5nfppgnjiqi0jg8er5n1nqhfek4q3qq.apps.googleusercontent.com',
    iosBundleId: 'com.example.voyage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAopEj_RbeDes8NtR0iyJ9hAOcoM5z7xSg',
    appId: '1:565579818314:ios:9ac2476754f59108878db3',
    messagingSenderId: '565579818314',
    projectId: 'voyage-73bab',
    storageBucket: 'voyage-73bab.appspot.com',
    iosClientId: '565579818314-a5nfppgnjiqi0jg8er5n1nqhfek4q3qq.apps.googleusercontent.com',
    iosBundleId: 'com.example.voyage',
  );
}
